---
kind: pipeline
name: default

steps:
  - name: build
    image: golang
    commands:
      - go generate
      - go build

  - name: build image
    image: plugins/docker

trigger:
  branch:
    - master
