---
kind: pipeline
name: default

steps:
  - name: build
    image: golang
    commands:
      - go generate
      - go build

  - name: build image
    image: plugins/docker
    settings:
      registry: r.anetz.net
      username: robot$test
      password: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTAyOTg4NDIsImlhdCI6MTYwNzcwNjg0MiwiaXNzIjoiaGFyYm9yLXRva2VuLWRlZmF1bHRJc3N1ZXIiLCJpZCI6MiwicGlkIjoyLCJhY2Nlc3MiOlt7IlJlc291cmNlIjoiL3Byb2plY3QvMi9yZXBvc2l0b3J5IiwiQWN0aW9uIjoicHVzaCIsIkVmZmVjdCI6IiJ9XX0.Nz5JPWoFyZI1e0wzc3ZQKp5nQdmxT2c4Xl2yZU4QPFNVhRvyiRXQW9smRwiPMxk1eYA9yAePimjEVKlCdDnFDQ3yk5i8xI5JYuPNcUiCAvrD50Rb_3xrVBhfCnvHweAB0EP5KKTuH1SGPUmP0SF7XYNVLN1mdMjcMjHAZur74pka8MsSUKw1ZQOpR1U6D08mmIRvNqJGcNOTAweSrFRjTyzPtQQx-Qrh0guoWsJ5xI-K7uCiGvp4j8wqCc0G8ep88N-jtKFewjgHUlkVXAnKXuFL1cMYHDoddg8hfW_S8byL28gMlWe-0Lx3DywoPUgMgSgGSEqe8BFaL9FmXMqKkjKllMIhRSIzVGGTd7C88shlZi9ouZnmIpdXzTi_bgmV655vEnZfIynzCcAsgX47X9TuA5F7i2A8BYp8QOo8M-OOSSZCeZVSXziDZm7E-DNYjQlEnY_pcv84oab9lQ7bcIXElfkLdVGcEd4HzLMXYa4QhjoBLxEdE8sbg1aVd2JC4otyqzPPyE7zPX8j-BVjXHiAwcx5fuC0USdVlyepO5c59xxnXkCPn_Axf7T77dx_cMTiX_-eu9s5epxyN1HaNDhta0CoodYevla6HuuSwgYKbsshCuWnzrvEMm6j0uxHpyJCSk0pHZRxU9YAYqA2xlV7OBpyUnye-3pEdj4oygo
      repo: r.anetz.net/anetz/coredns
      tags: latest

trigger:
  branch:
    - master
